<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.globaltrade.scms</groupId>
        <artifactId>globaltrade-scms-parent</artifactId>
        <version>1.0.0</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>

    <artifactId>scms-web</artifactId>
    <packaging>war</packaging>

    <name>SCMS Web Module</name>

    <dependencies>

        <dependency>
            <groupId>com.globaltrade.scms</groupId>
            <artifactId>scms-common</artifactId>
            <scope>provided</scope>
        </dependency>
<!--postgresql-42.7.11.jar-->
        <dependency>
            <groupId>com.globaltrade.scms</groupId>
            <artifactId>scms-ejb-api</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>jakarta.platform</groupId>
            <artifactId>jakarta.jakartaee-api</artifactId>
            <scope>provided</scope>
        </dependency>

    </dependencies>

    <build>
        <finalName>scms-web</finalName>
    </build>

</project>
